/*3D係数学を扱う秀丸マクロ

全部あり版
メニューから動作を選択
アウトプット枠へ出力
*/

$g_filename_get = currentmacrodirectory + "\\" + "math_3d_get_values.mac";
$g_filename_run = currentmacrodirectory + "\\" + "math_3d_run.mac";
call Main;
endmacro;


Main:
	execmacro $g_filename_get;
	$$args = getresultex(-1);
	if(! strlen($$args)){
		return false;
	}
	
	$$mode = "f32_hex";
	execmacro $g_filename_run, $$mode, $$args;
	##ret = val(getresultex(-1));
	return ##ret;

	